name: Deploy Server

on:
  push:
    branches:
      - master
    paths:
      - "src/*"
      - ".github/workflows/DeployServer.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "hi from github workflow"
      - name: get repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: add github username
        run: git config --global user.name "Sakshi23-08"
      - name: add github email
        run: git config --global user.email "sakshigmasurkar@gmail.com"
      - name: add heroku remote
        run: git remote add heroku https://heroku:3fb8c44c-3d68-42be-b452-e04d146832f7@git.heroku.com/aqueous-fjord-75836.git
      - name: push to heroku
        run: git push heroku master --force